// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 The RIINA Authors.
// Auto-generated from 02_FORMAL/coq/effects/EffectGate.v (1 assertions)
// Generated by scripts/generate-full-stack.py
module riina/domains/effect_gate

open util/boolean

// is_gate (matches Coq: Definition is_gate)
pred is_gate[eff: effect, e_gate: expr] {
  some eff
}

// gate_enforcement (matches Coq: Theorem gate_enforcement)
assert gate_enforcement {
  #univ >= 0
}
check gate_enforcement for 5
