(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)
(* Auto-generated from 02_FORMAL/coq/properties/check_ax.v (0 lemmas) *)
(* Generated by scripts/generate-full-stack.py *)
module RIINA.Domains.check_ax
open FStar.All
