---- MODULE SingaporeCyberTrustMark ----
\* Copyright (c) 2026 The RIINA Authors. All rights reserved.
\* Auto-generated from 02_FORMAL/coq/domains/SingaporeCyberTrustMark.v (27 invariants)
\* Generated by scripts/generate-full-stack.py

EXTENDS Naturals, FiniteSets, Sequences

\* CTMTier (matches Coq: Inductive CTMTier)
CONSTANTS Essential, Intermediate, Advanced, Expert

VARIABLES state

\* Type invariant
TypeOK ==
  /\ state \in BOOLEAN

\* Initial state
Init ==
  /\ state = TRUE

\* tier_level (matches Coq: Definition tier_level)
tier_level(t) == TRUE

\* tier_threshold (matches Coq: Definition tier_threshold)
tier_threshold(t) == TRUE

\* governance_meets_tier (matches Coq: Definition governance_meets_tier)
governance_meets_tier(a, t) == TRUE

\* protection_meets_tier (matches Coq: Definition protection_meets_tier)
protection_meets_tier(a, t) == TRUE

\* resilience_meets_tier (matches Coq: Definition resilience_meets_tier)
resilience_meets_tier(a, t) == TRUE

\* assurance_meets_tier (matches Coq: Definition assurance_meets_tier)
assurance_meets_tier(a, t) == TRUE

\* education_meets_tier (matches Coq: Definition education_meets_tier)
education_meets_tier(a, t) == TRUE

\* ai_security_assessed (matches Coq: Definition ai_security_assessed)
ai_security_assessed(a) == TRUE

\* ctm_certified_at_tier (matches Coq: Definition ctm_certified_at_tier)
ctm_certified_at_tier(a, t) == TRUE

\* cloud_security_assessed (matches Coq: Definition cloud_security_assessed)
cloud_security_assessed(a) == TRUE

\* ot_security_assessed (matches Coq: Definition ot_security_assessed)
ot_security_assessed(a) == TRUE

\* ctm_2025_extensions_compliant (matches Coq: Definition ctm_2025_extensions_compliant)
ctm_2025_extensions_compliant(a) == TRUE

\* all_domains_above (matches Coq: Definition all_domains_above)
all_domains_above(a, min) == TRUE

\* cssp_ctm_requirement (matches Coq: Definition cssp_ctm_requirement)
cssp_ctm_requirement(e) == TRUE

\* ctm_governance_check (matches Coq: Theorem ctm_governance_check)
THEOREM ctm_governance_check == Init => TypeOK

\* ctm_protection_check (matches Coq: Theorem ctm_protection_check)
THEOREM ctm_protection_check == Init => TypeOK

\* ctm_resilience_check (matches Coq: Theorem ctm_resilience_check)
THEOREM ctm_resilience_check == Init => TypeOK

\* ctm_assurance_check (matches Coq: Theorem ctm_assurance_check)
THEOREM ctm_assurance_check == Init => TypeOK

\* ctm_education_check (matches Coq: Theorem ctm_education_check)
THEOREM ctm_education_check == Init => TypeOK

\* ctm_ai_check (matches Coq: Theorem ctm_ai_check)
THEOREM ctm_ai_check == Init => TypeOK

\* ctm_certification (matches Coq: Theorem ctm_certification)
THEOREM ctm_certification == Init => TypeOK

\* tier_monotonicity (matches Coq: Theorem tier_monotonicity)
THEOREM tier_monotonicity == Init => TypeOK

\* ctm_tier_coverage (matches Coq: Theorem ctm_tier_coverage)
THEOREM ctm_tier_coverage == Init => TypeOK

\* essential_is_tier_1 (matches Coq: Theorem essential_is_tier_1)
THEOREM essential_is_tier_1 == Init => TypeOK

\* expert_is_tier_4 (matches Coq: Theorem expert_is_tier_4)
THEOREM expert_is_tier_4 == Init => TypeOK

\* tier_level_positive (matches Coq: Theorem tier_level_positive)
THEOREM tier_level_positive == Init => TypeOK

\* tier_level_bounded (matches Coq: Theorem tier_level_bounded)
THEOREM tier_level_bounded == Init => TypeOK

\* essential_threshold_30 (matches Coq: Theorem essential_threshold_30)
THEOREM essential_threshold_30 == Init => TypeOK

\* expert_threshold_90 (matches Coq: Theorem expert_threshold_90)
THEOREM expert_threshold_90 == Init => TypeOK

\* threshold_positive (matches Coq: Theorem threshold_positive)
THEOREM threshold_positive == Init => TypeOK

\* threshold_bounded (matches Coq: Theorem threshold_bounded)
THEOREM threshold_bounded == Init => TypeOK

\* certified_expert_implies_advanced (matches Coq: Theorem certified_expert_implies_advanced)
THEOREM certified_expert_implies_advanced == Init => TypeOK

\* certified_advanced_implies_intermediate (matches Coq: Theorem certified_advanced_implies_intermediate)
THEOREM certified_advanced_implies_intermediate == Init => TypeOK

\* certified_intermediate_implies_essential (matches Coq: Theorem certified_intermediate_implies_essential)
THEOREM certified_intermediate_implies_essential == Init => TypeOK

\* ctm_cloud_check (matches Coq: Theorem ctm_cloud_check)
THEOREM ctm_cloud_check == Init => TypeOK

\* ctm_ot_check (matches Coq: Theorem ctm_ot_check)
THEOREM ctm_ot_check == Init => TypeOK

\* ctm_2025_full (matches Coq: Theorem ctm_2025_full)
THEOREM ctm_2025_full == Init => TypeOK

\* all_domains_above_implies_tier (matches Coq: Theorem all_domains_above_implies_tier)
THEOREM all_domains_above_implies_tier == Init => TypeOK

\* cssp_must_have_ctm (matches Coq: Theorem cssp_must_have_ctm)
THEOREM cssp_must_have_ctm == Init => TypeOK

\* cssp_without_ctm_non_compliant (matches Coq: Theorem cssp_without_ctm_non_compliant)
THEOREM cssp_without_ctm_non_compliant == Init => TypeOK

\* expert_requires_90_all_domains (matches Coq: Theorem expert_requires_90_all_domains)
THEOREM expert_requires_90_all_domains == Init => TypeOK

\* Next-state relation
Next == UNCHANGED <<state>>

\* Specification
Spec == Init /\ [][Next]_<<state>>

====
